name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Exécuter une fois par jour
  workflow_dispatch: # Permet de lancer manuellement le workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Snake Animation
      uses: Platane/snk@v3
      with:
        github_user_name: Benalgodev # Remplace par ton nom d'utilisateur
        output: dist/github-contribution-grid-snake.svg

    - name: Upload Animation
      uses: actions/upload-artifact@v3
      with:
        name: snake-animation
        path: dist/github-contribution-grid-snake.svg
